baseURL = "https://KIHeartFailure.github.io/shfdb3/"
title = "SHFDB3"
theme = "hugo-theme-zdoc"

publishDir = "./docs"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = false

copyright = "Contact: lina.benson@ki.se."
timeout = 10000
enableEmoji = true
paginate = 13
rssLimit = 100

googleAnalytics = "UA-164909329-1"

disableKinds = ["taxonomyTerm"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
